### ISSUE TITLE
values become mixed

### ISSUE THREAD

**Issue by rikki78** [hvdwolf/pimatic-knmi#1]
Hello Harry,

first of all thanks for this nice script. I'm new into python so I hope you can help. The values read from knmi become mixed: I've added a print in the script and now I see this output:
You can see the humidity and chill factor are on the same line. How can I correct this?
 9.7
5.6 80
 ZZW
 11
 22000

```
{
  "variable": {
    "name": "knmi-locatie",
    "readonly": false,
    "type": "value",
    "value": "Berkhout",
    "unit": ""
  },
  "success": true
}{
  "variable": {
    "name": "knmi-temperatuur",
    "readonly": false,
    "type": "value",
    "value": 9.7,
    "unit": ""
  },
  "success": true
}{
  "variable": {
    "name": "knmi-chill",
    "readonly": false,
    "type": "value",
    "value": 5.68,
    "unit": ""
  },
  "success": true
}{
  "variable": {
    "name": "knmi-rv",
    "readonly": false,
    "type": "value",
    "value": "ZZW",
    "unit": ""
  },
  "success": true
}{
  "variable": {
    "name": "knmi-wr",
    "readonly": false,
    "type": "value",
    "value": 11,
    "unit": ""
  },
  "success": true
}{
  "variable": {
    "name": "knmi-ws",
    "readonly": false,
    "type": "value",
    "value": 22000,
    "unit": ""
  },
  "success": true
}{
  "variable": {
    "name": "knmi-zicht",
    "readonly": false,
    "type": "value",
    "value": "",
    "unit": ""
  },
  "success": true
```

**Comment by hvdwolf** [comment]
Hi, I did see the same. I'm currently rewriting the script to correct that and to add some more functionality but I let it rest for 2 weeks or so due to a busy schedule. I wanted to pickup again this weekend. I try to get back as soon as possible

**Comment by hvdwolf** [comment]
Hi,

I finished the rewrite of the script. The error was due to the fact that the chill factor was added. And it was not done in a nice way.
The script is now working again although it complains about numerical values somethimes being empty. Maybe I will change them to strings.

**Comment by rikki78** [comment]
sorry for the late reply but your update has solved this!
